/*
 * Code generated from Atmel Start.
 *
 * This file will be overwritten when reconfiguring your Atmel Start project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */
#ifndef ATMEL_START_PINS_H_INCLUDED
#define ATMEL_START_PINS_H_INCLUDED

#include <hal_gpio.h>

// SAMD51 has 14 pin functions

#define GPIO_PIN_FUNCTION_A 0
#define GPIO_PIN_FUNCTION_B 1
#define GPIO_PIN_FUNCTION_C 2
#define GPIO_PIN_FUNCTION_D 3
#define GPIO_PIN_FUNCTION_E 4
#define GPIO_PIN_FUNCTION_F 5
#define GPIO_PIN_FUNCTION_G 6
#define GPIO_PIN_FUNCTION_H 7
#define GPIO_PIN_FUNCTION_I 8
#define GPIO_PIN_FUNCTION_J 9
#define GPIO_PIN_FUNCTION_K 10
#define GPIO_PIN_FUNCTION_L 11
#define GPIO_PIN_FUNCTION_M 12
#define GPIO_PIN_FUNCTION_N 13

#define DISPLAY_MOSI GPIO(GPIO_PORTA, 0)
#define DISPLAY_SCK GPIO(GPIO_PORTA, 1)
#define PVD_CRNT GPIO(GPIO_PORTA, 2)
#define PHD_1 GPIO(GPIO_PORTA, 3)
#define PHD_4 GPIO(GPIO_PORTA, 4)
#define PHD_5 GPIO(GPIO_PORTA, 5)
#define PHD_6 GPIO(GPIO_PORTA, 6)
#define PHD_7 GPIO(GPIO_PORTA, 7)
#define PHD_8 GPIO(GPIO_PORTA, 8)
#define PHD_9 GPIO(GPIO_PORTA, 9)
#define PHD_10 GPIO(GPIO_PORTA, 10)
#define PHD_11 GPIO(GPIO_PORTA, 11)
#define MAGNETOMETER_GYRO_SCK GPIO(GPIO_PORTA, 12)
#define MAGNETOMETER_GYRO_MOSI GPIO(GPIO_PORTA, 13)
#define CAMERA_MISO GPIO(GPIO_PORTA, 14)
#define LED_ORANGE2 GPIO(GPIO_PORTA, 15)
#define SBAND_SCL GPIO(GPIO_PORTA, 16)
#define SBAND_SDA GPIO(GPIO_PORTA, 17)
#define DISPLAY_MISO GPIO(GPIO_PORTA, 18)
#define LED_RED GPIO(GPIO_PORTA, 19)
#define PA20 GPIO(GPIO_PORTA, 20)
#define PA21 GPIO(GPIO_PORTA, 21)
#define PA22 GPIO(GPIO_PORTA, 22)
#define PA23 GPIO(GPIO_PORTA, 23)
#define PHD_12 GPIO(GPIO_PORTB, 0)
#define PHD_13 GPIO(GPIO_PORTB, 1)
#define PHD_14 GPIO(GPIO_PORTB, 2)
#define PHD_15 GPIO(GPIO_PORTB, 3)
#define THERM_0 GPIO(GPIO_PORTB, 4)
#define THERM_1 GPIO(GPIO_PORTB, 5)
#define PB06 GPIO(GPIO_PORTB, 6)
#define PB07 GPIO(GPIO_PORTB, 7)
#define PHD_2 GPIO(GPIO_PORTB, 8)
#define PHD_3 GPIO(GPIO_PORTB, 9)
#define MRAM3_CS GPIO(GPIO_PORTB, 10)
#define MRAM3_RST GPIO(GPIO_PORTB, 11)
#define MRAM1_WP GPIO(GPIO_PORTB, 12)
#define MRAM2_WP GPIO(GPIO_PORTB, 13)
#define MAGNETOMETER_GYRO_MISO GPIO(GPIO_PORTB, 14)
#define MRAM3_WP GPIO(GPIO_PORTB, 15)
#define SBAND_MOSI GPIO(GPIO_PORTB, 16)
#define SBAND_SCK GPIO(GPIO_PORTB, 17)
#define SBAND_MISO GPIO(GPIO_PORTB, 18)
#define BURN GPIO(GPIO_PORTB, 19)
#define EPS_RST GPIO(GPIO_PORTB, 20)
#define EPS_A0 GPIO(GPIO_PORTB, 21)
#define EPS_A1 GPIO(GPIO_PORTB, 22)
#define EPS_A3 GPIO(GPIO_PORTB, 23)
#define MRAM_MOSI GPIO(GPIO_PORTB, 24)
#define MRAM_SCK GPIO(GPIO_PORTB, 25)
#define CAMERA_MOSI GPIO(GPIO_PORTB, 26)
#define CAMERA_SCK GPIO(GPIO_PORTB, 27)
#define EPS_IRQ GPIO(GPIO_PORTB, 28)
#define MTQ_X_SLP GPIO(GPIO_PORTB, 30)
#define MTQ_Y_SLP GPIO(GPIO_PORTB, 31)
#define PHD_0 GPIO(GPIO_PORTC, 0)
#define PC01 GPIO(GPIO_PORTC, 1)
#define PHD_16 GPIO(GPIO_PORTC, 2)
#define PHD_17 GPIO(GPIO_PORTC, 3)
#define MRAM1_CS GPIO(GPIO_PORTC, 4)
#define MRAM1_RST GPIO(GPIO_PORTC, 5)
#define MRAM2_CS GPIO(GPIO_PORTC, 6)
#define MRAM2_RST GPIO(GPIO_PORTC, 7)
#define MAGNETOMETER_DRDY GPIO(GPIO_PORTC, 10)
#define DISPLAY_CS GPIO(GPIO_PORTC, 11)
#define UHF_MOSI GPIO(GPIO_PORTC, 12)
#define UHF_SCK GPIO(GPIO_PORTC, 13)
#define CAMERA_CS GPIO(GPIO_PORTC, 14)
#define LED_ORANGE1 GPIO(GPIO_PORTC, 15)
#define UHF_CS GPIO(GPIO_PORTC, 16)
#define UHF_RST GPIO(GPIO_PORTC, 17)
#define MRAM_MISO GPIO(GPIO_PORTC, 18)
#define MAGNETOMETER_CS GPIO(GPIO_PORTC, 19)
#define GYRO_CS GPIO(GPIO_PORTC, 20)
#define HEATER_CTRL_1 GPIO(GPIO_PORTC, 23)
#define HEATER_CTRL_2 GPIO(GPIO_PORTC, 24)
#define MTQ_Z_SLP GPIO(GPIO_PORTC, 27)
#define PC30 GPIO(GPIO_PORTC, 30)
#define PC31 GPIO(GPIO_PORTC, 31)
#define THERM_2 GPIO(GPIO_PORTD, 0)
#define THERM_3 GPIO(GPIO_PORTD, 1)
#define CAMERA_SCL GPIO(GPIO_PORTD, 8)
#define CAMERA_SDA GPIO(GPIO_PORTD, 9)
#define UHF_MISO GPIO(GPIO_PORTD, 10)
#define DISPLAY_RST GPIO(GPIO_PORTD, 11)
#define DISPLAY_DC GPIO(GPIO_PORTD, 12)
#define PD20 GPIO(GPIO_PORTD, 20)
#define PD21 GPIO(GPIO_PORTD, 21)

#endif // ATMEL_START_PINS_H_INCLUDED
