#!/bin/bash


# $(SED) -i 's|#define configCHECK_FOR_STACK_OVERFLOW 1|#define configCHECK_FOR_STACK_OVERFLOW 2|' ./FreeRTOSConfig.h \

# sed -i 'a/#define INCLUDE_xTaskGetIdleTaskHandle 0\n#endif/ #define NEW_MACRO 42' ./FreeRTOSConfig.h

# sed -i '/#define INCLUDE_xTaskGetCurrentTaskHandle 0/ {N /#endif/ a \ \ // \<q\> Include thread-local storage pointers \ // \<id\> freertos_num_thread_local_storage_pointers \
# #ifndef configNUM_THREAD_LOCAL_STORAGE_POINTERS \
# #define configNUM_THREAD_LOCAL_STORAGE_POINTERS 1 \
# #endif
# }' ./FreeRTOSConfig.h

sed -i '/#define INCLUDE_xTaskGetCurrentTaskHandle 0/ {
  N
  /#endif/ a \
\
// \<q\> Include thread-local storage pointers \
// \<id\> freertos_num_thread_local_storage_pointers \
#ifndef configNUM_THREAD_LOCAL_STORAGE_POINTERS \
#define configNUM_THREAD_LOCAL_STORAGE_POINTERS 1 \
#endif
}' ./FreeRTOSConfig.h
