/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_simple_assert(void);
extern void test_addition(void);
extern void test_addition_failure(void);

/*=======Mock Management=====*/
static void CMock_Init(void) {}
static void CMock_Verify(void) {}
static void CMock_Destroy(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void) {
    tearDown();
    CMock_Verify();
    CMock_Destroy();
    CMock_Init();
    setUp();
}
void verifyTest(void);
void verifyTest(void) { CMock_Verify(); }

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char *name,
                     UNITY_LINE_TYPE line_num) {
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches()) return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT()) {
        setUp();
        func();
    }
    if (TEST_PROTECT()) {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void) {
    UnityBegin("./test-tests/test_tests.c");
    run_test(test_simple_assert, "test_simple_assert", 18);
    run_test(test_addition, "test_addition", 23);
    run_test(test_addition_failure, "test_addition_failure", 25);

    return UnityEnd();
}
